In [2]:
import pandas as pd

catagory = pd.read_excel("catagory.xlsx")
post = pd.read_excel("posts.xlsx")

In [3]:
catagory.head()

,No.,category_id,หมวด,status scarp,sub-category,num_page,scarp_Date,link_raw_data,link_cleaned_data,TotalRow,...,AVG_Num_Sold,AVG_Hire_Repeat,AVG_Hire_Repeat_Percentage,Total_ZeroNum_SoldAndRepeatedHire,Total_ZeroNum_SoldAndRepeatedHire_Percentage,Max_Num_Comment,AVG_Num_Comment,sitemap_1,sitemap_2,sitemap_3
0,1,graphic_design,ออกแบบกราฟิก,ok,29,408,2024-06-11,https://docs.google.com/spreadsheets/d/1QAArQX...,https://docs.google.com/spreadsheets/d/1ZTt358...,16251,...,27.084402,8.004727,0.295547,588,0.011315,906,30.813639,"{""_id"":""design-graphic"",""startUrl"":[""https://f...","{""_id"":""design-graphic_2"",""startUrl"":[""https:/...","{""_id"":""design-graphic_3"",""startUrl"":[""https:/..."
1,2,Marketing_and_advertising\n,การตลาดและโฆษณา,ok,21,102,2024-06-13,https://docs.google.com/spreadsheets/d/1diaRTm...,https://docs.google.com/spreadsheets/d/1UAgXT7...,3935,...,30.620296,9.599772,0.313510,360,0.010206,977,35.838084,"{""_id"":""marketing-advertising"",""startUrl"":[""ht...","{""_id"":""marketing-advertising_2"",""startUrl"":[""...",-
2,3,Website_and_technology\n,เว็บไซต์และเทคโนโลยี,ok,18,97,2024-06-13,https://docs.google.com/spreadsheets/d/1HD5G1l...,https://docs.google.com/spreadsheets/d/17-Oan8...,3781,...,20.189580,7.370478,0.365063,246,0.012917,639,16.131693,"{""_id"":""web-programming"",""startUrl"":[""https://...","{""_id"":""web-programming_2"",""startUrl"":[""https:...",-
3,4,Lifestyle\n,ไลฟ์สไตล์,ok,14,41,2024-06-17,https://docs.google.com/spreadsheets/d/1LqJeoq...,https://docs.google.com/spreadsheets/d/12gZv-h...,1489,...,20.189580,7.370478,0.126991,193,0.038423,539,9.180412,"{""_id"":""lifestyle"",""startUrl"":[""https://fastwo...",-,-
4,5,Image_and_sound,ภาพและเสียง,ok,13,101,2024-06-13,https://docs.google.com/spreadsheets/d/1TMRej3...,https://docs.google.com/spreadsheets/d/1xlc3FR...,4048,...,27.442827,10.765073,0.392273,157,0.008543,887,27.220374,"{""_id"":""photography-video"",""startUrl"":[""https:...",-,-

# post

In [55]:
post.head()

,Post_ID,category_id,sub_category,title,namefreelance,web-scraper-order,web-scraper-start-url,link,rating_comment,Num_comment,percentsuccess,cost,num_sold,repeat hired
0,1,Architecture_and_Engineering,home-inspection,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,columbias,1718528605-1,https://fastwork.co/home-inspection?source=cat...,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,0.0,0,-,2500,0,0
1,2,Architecture_and_Engineering,home-inspection,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,supakorn95,1718528607-2,https://fastwork.co/home-inspection?source=cat...,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,0.0,0,-,2500,0,0
2,3,Architecture_and_Engineering,home-inspection,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,wankhayai,1718528609-3,https://fastwork.co/home-inspection?source=cat...,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,0.0,0,-,3500,0,0
3,4,Architecture_and_Engineering,home-inspection,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,warunyoo,1718528611-4,https://fastwork.co/home-inspection?source=cat...,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,0.0,0,-,2500,0,0
4,5,Architecture_and_Engineering,home-inspection,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,billphusit,1718528614-5,https://fastwork.co/home-inspection?source=cat...,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,0.0,0,-,3500,0,0

In [56]:
# Create a DataFrame
df = post

# Function to extract the desired part of the URL
def extract_part(url):
    start = len("https://fastwork.co/")
    end = url.find("?source=category_architect")
    word = url[start:end]
    return word.split('?')[0]

# Apply the function to the 'F' column and create a new 'G' column
df['sub_category'] = df['web-scraper-start-url'].apply(extract_part)

# Display the DataFrame
df.head()

,Post_ID,category_id,sub_category,title,namefreelance,web-scraper-order,web-scraper-start-url,link,rating_comment,Num_comment,percentsuccess,cost,num_sold,repeat hired
0,1,Architecture_and_Engineering,home-inspection,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,columbias,1718528605-1,https://fastwork.co/home-inspection?source=cat...,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,0.0,0,-,2500,0,0
1,2,Architecture_and_Engineering,home-inspection,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,supakorn95,1718528607-2,https://fastwork.co/home-inspection?source=cat...,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,0.0,0,-,2500,0,0
2,3,Architecture_and_Engineering,home-inspection,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,wankhayai,1718528609-3,https://fastwork.co/home-inspection?source=cat...,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,0.0,0,-,3500,0,0
3,4,Architecture_and_Engineering,home-inspection,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,warunyoo,1718528611-4,https://fastwork.co/home-inspection?source=cat...,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,0.0,0,-,2500,0,0
4,5,Architecture_and_Engineering,home-inspection,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,billphusit,1718528614-5,https://fastwork.co/home-inspection?source=cat...,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,0.0,0,-,3500,0,0

In [57]:
columns_to_keep = ['Post_ID','category_id',	'sub_category','title',	'namefreelance','web-scraper-order'	,'web-scraper-start-url','link', 'rating_comment','Num_comment','percentsuccess','cost','num_sold','repeat hired']
post = post[columns_to_keep]
post.head()

,Post_ID,category_id,sub_category,title,namefreelance,web-scraper-order,web-scraper-start-url,link,rating_comment,Num_comment,percentsuccess,cost,num_sold,repeat hired
0,1,Architecture_and_Engineering,home-inspection,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,columbias,1718528605-1,https://fastwork.co/home-inspection?source=cat...,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,0.0,0,-,2500,0,0
1,2,Architecture_and_Engineering,home-inspection,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,supakorn95,1718528607-2,https://fastwork.co/home-inspection?source=cat...,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,0.0,0,-,2500,0,0
2,3,Architecture_and_Engineering,home-inspection,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,wankhayai,1718528609-3,https://fastwork.co/home-inspection?source=cat...,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,0.0,0,-,3500,0,0
3,4,Architecture_and_Engineering,home-inspection,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,warunyoo,1718528611-4,https://fastwork.co/home-inspection?source=cat...,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,0.0,0,-,2500,0,0
4,5,Architecture_and_Engineering,home-inspection,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,billphusit,1718528614-5,https://fastwork.co/home-inspection?source=cat...,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,0.0,0,-,3500,0,0

In [58]:
output_file = "posts.xlsx"
post.to_excel(output_file, index=False, engine='openpyxl')
print(f"Merged data has been saved to {output_file}")

Merged data has been saved to posts.xlsx

# user

In [59]:

columns_to_keep = ['namefreelance', 'category_id','sub_category','num_sold', 'repeat hired','rating_comment', 'Num_comment','cost']
aboutUsers = post[columns_to_keep]

In [60]:
aboutUsers.head()

,namefreelance,category_id,sub_category,num_sold,repeat hired,rating_comment,Num_comment,cost
0,columbias,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500
1,supakorn95,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500
2,wankhayai,Architecture_and_Engineering,home-inspection,0,0,0.0,0,3500
3,warunyoo,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500
4,billphusit,Architecture_and_Engineering,home-inspection,0,0,0.0,0,3500

In [61]:
# Create DataFrame
df = aboutUsers

# Ensure numeric columns are of appropriate numeric type
df['num_sold'] = pd.to_numeric(df['num_sold'])
df['repeat hired'] = pd.to_numeric(df['repeat hired'])
df['rating_comment'] = pd.to_numeric(df['rating_comment'])
df['Num_comment'] = pd.to_numeric(df['Num_comment'])
df['cost'] = pd.to_numeric(df['cost'])

grouped_df = df.groupby(['namefreelance', 'category_id', 'sub_category']).agg(
    Total_Cost_userGain=pd.NamedAgg(column='cost', aggfunc='sum'),
    Total_Sum_User_Sold=pd.NamedAgg(column='num_sold', aggfunc='sum'),
    Total_Hire_Repeat_User=pd.NamedAgg(column='repeat hired', aggfunc='sum'),
    User_Rating_Comment=pd.NamedAgg(column='rating_comment', aggfunc='mean'),
    User_Num_Comment=pd.NamedAgg(column='Num_comment', aggfunc='sum'),

).reset_index()

# Calculate additional columns
grouped_df

/var/folders/_y/8lknr6bn3pdd9d4pzpmjtszh0000gn/T/ipykernel_53600/343913726.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_sold'] = pd.to_numeric(df['num_sold'])
/var/folders/_y/8lknr6bn3pdd9d4pzpmjtszh0000gn/T/ipykernel_53600/343913726.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['repeat hired'] = pd.to_numeric(df['repeat hired'])
/var/folders/_y/8lknr6bn3pdd9d4pzpmjtszh0000gn/T/ipykernel_53600/343913726.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating_comment'] = pd.to_numeric(df['rating_comment'])
/var/folders/_y/8lknr6bn3pdd9d4pzpmjtszh0000gn/T/ipykernel_53600/343913726.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Num_comment'] = pd.to_numeric(df['Num_comment'])
/var/folders/_y/8lknr6bn3pdd9d4pzpmjtszh0000gn/T/ipykernel_53600/343913726.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cost'] = pd.to_numeric(df['cost'])

,namefreelance,category_id,sub_category,Total_Cost_userGain,Total_Sum_User_Sold,Total_Hire_Repeat_User,User_Rating_Comment,User_Num_Comment
0,0racle,Write_and_translate,desktop-application,3000,53,9,4.8,43
1,0racle,Write_and_translate,web-scraping,3000,2,0,4.2,1
2,100karat,Write_and_translate,web-development,10000,1,0,5.0,1
3,100karat,Write_and_translate,web-programming-other,1500,3,0,5.0,3
4,111butart,Graphic_design,illustration,500,8,3,4.7,3
...,...,...,...,...,...,...,...,...
4160,่Jittarawadee,Business_and_consulting,accounting-and-finance,2500,3,0,5.0,3
4161,๋Jida24,Graphic_design,cartoon-drawing,500,22,8,4.9,16
4162,๋Jida24,Graphic_design,illustration-portrait,750,87,9,4.9,75
4163,์NathapanuS,Lifestyle,singer-band,6000,0,0,0.0,0
4164,์NathapanuS,Marketing_and_advertising,promote-real-estate,500,5,1,4.6,3

In [62]:
output_file = "aboutUser.xlsx"
grouped_df.to_excel(output_file, index=False, engine='openpyxl')
print(f"Merged data has been saved to {output_file}")

Merged data has been saved to aboutUser.xlsx

# Title

In [74]:
columns_to_keep = ['title', 'Post_ID','category_id','sub_category','num_sold', 'repeat hired','rating_comment', 'Num_comment','cost']
aboutTitle = post[columns_to_keep]

In [75]:
aboutTitle

,title,Post_ID,category_id,sub_category,num_sold,repeat hired,rating_comment,Num_comment,cost
0,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,1,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500
1,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,2,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500
2,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,3,Architecture_and_Engineering,home-inspection,0,0,0.0,0,3500
3,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,4,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500
4,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,5,Architecture_and_Engineering,home-inspection,0,0,0.0,0,3500
...,...,...,...,...,...,...,...,...,...
4937,รับพิมพ์และทำรายงานด่วน (ภาษาไทยและภาษาอังกฤษ),4938,Write_and_translate,typing-and-data-entry,104,39,4.8,79,300
4938,จัดรูปแบบวิทยานิพนธ์ i-thesis / Endnote / บทความ,4939,Write_and_translate,typing-and-data-entry,144,8,4.9,92,250
4939,จัดหน้าเอกสารธีสิส งานวิจัย รายงาน บทความอวิทย...,4940,Write_and_translate,typing-and-data-entry,2,0,5.0,2,500
4940,พิมพ์เอกสาร พร้อมจัดรูปแบบข้อความ,4941,Write_and_translate,typing-and-data-entry,0,0,4.9,9,300
4941,รับพิมพ์และทำรายงานด่วน (ภาษาไทยและภาษาอังกฤษ),4942,Write_and_translate,typing-and-data-entry,0,0,4.8,79,300

In [67]:
pip install pythainlp

Collecting pythainlp
  Downloading pythainlp-5.0.4-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: requests>=2.22.0 in /opt/anaconda3/lib/python3.11/site-packages (from pythainlp) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.22.0->pythainlp) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.22.0->pythainlp) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.22.0->pythainlp) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.11/site-packages (from requests>=2.22.0->pythainlp) (2024.2.2)
Downloading pythainlp-5.0.4-py3-none-any.whl (17.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 17.7 MB/s eta 0:00:0000:0100:01
Installing collected packages: pythainlp
Successfully installed pythainlp-5.0.4
Note: you may need to restart the kernel to use updated packages.

In [81]:
from pythainlp import word_tokenize
from collections import Counter

# Function to split English and Thai words
def split_words(sentence):
    english_words = []
    thai_words = []
    for word in sentence.split():
        if any(char.isalpha() for char in word) and all(char.isascii() for char in word):
            english_words.extend(word.split())
        else:
            thai_words.extend(word_tokenize(word))
    return english_words + thai_words

# Split words for each title in the aboutTitle['title']
all_words = []
for title in aboutTitle['title']:
    all_words.extend(split_words(title))

# Count the frequency of each word
word_counts = Counter(all_words)

# Sort the words by frequency and get the top 100 words with their counts
top_100_words = word_counts.most_common(100)

# Create a DataFrame from the top 100 words
df_top_100 = pd.DataFrame(top_100_words, columns=['Word', 'Count'])

# Save the DataFrame to an Excel file
output_file = "top_100_famous_words.xlsx"
df_top_100.to_excel(output_file, index=False, engine='openpyxl')

print(f"Top 100 famous words have been saved to {output_file}")

Top 100 famous words have been saved to top_100_famous_words.xlsx

In [82]:
topWord = pd.read_excel("top_100_famous_words.xlsx")

In [83]:
topWord["Word"]

0         รับ
1         และ
2           /
3      ออกแบบ
4          ทำ
       ...
95        รูป
96      พัฒนา
97        จัด
98    โปรแกรม
99      แก้ไข
Name: Word, Length: 100, dtype: object

In [87]:
# Add a new column "NumFamousWord" to aboutTitle
def count_famous_words(title, top_words):
    split_title_words = split_words(title)
    return sum(word in top_words for word in split_title_words)

# Convert top words to a set for faster lookup
top_words_set = set(topWord['Word'])

# Apply the count function to each title
aboutTitle['NumFamousWord'] = aboutTitle['title'].apply(lambda title: count_famous_words(title, top_words_set))

aboutTitle.head()

/var/folders/_y/8lknr6bn3pdd9d4pzpmjtszh0000gn/T/ipykernel_53600/940879016.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aboutTitle['NumFamousWord'] = aboutTitle['title'].apply(lambda title: count_famous_words(title, top_words_set))

,title,Post_ID,category_id,sub_category,num_sold,repeat hired,rating_comment,Num_comment,cost,NumFamousWord
0,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,1,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500,7
1,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,2,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500,7
2,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,3,Architecture_and_Engineering,home-inspection,0,0,0.0,0,3500,3
3,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,4,Architecture_and_Engineering,home-inspection,0,0,0.0,0,2500,2
4,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,5,Architecture_and_Engineering,home-inspection,0,0,0.0,0,3500,7

In [92]:
aboutTitle['lengthTitle'] = aboutTitle['title'].apply(len)

In [93]:
aboutTitle.head()

,title,Post_ID,category_id,sub_category,num_sold,NumFamousWord,repeat hired,rating_comment,Num_comment,cost,lengthTitle
0,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,1,Architecture_and_Engineering,home-inspection,0,7,0,0.0,0,2500,73
1,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,2,Architecture_and_Engineering,home-inspection,0,7,0,0.0,0,2500,63
2,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,3,Architecture_and_Engineering,home-inspection,0,3,0,0.0,0,3500,54
3,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,4,Architecture_and_Engineering,home-inspection,0,2,0,0.0,0,2500,72
4,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,5,Architecture_and_Engineering,home-inspection,0,7,0,0.0,0,3500,75

In [94]:
columns_to_keep = ['title', 'Post_ID','category_id','sub_category','NumFamousWord','lengthTitle','num_sold','repeat hired','rating_comment', 'Num_comment','cost']
aboutTitle = aboutTitle [columns_to_keep]

In [95]:
aboutTitle.head()

,title,Post_ID,category_id,sub_category,NumFamousWord,lengthTitle,num_sold,repeat hired,rating_comment,Num_comment,cost
0,ตรวจรับบ้านและคอนโดก่อนโอน โดยวิศวกรโยธา ระดับ...,1,Architecture_and_Engineering,home-inspection,7,73,0,0,0.0,0,2500
1,บริการให้คำปรึกษาพร้อมรับตรวจคอนโดโดยวิศวกรที่...,2,Architecture_and_Engineering,home-inspection,7,63,0,0,0.0,0,2500
2,แว่นขยาย บริการตรวจ defect ก่อนโอน โดยสถาปนิกแ...,3,Architecture_and_Engineering,home-inspection,3,54,0,0,0.0,0,3500
3,ตรวจคอนโด ตรวจบ้าน ตรวจอาคารพาณิชย์ ด้วยทีมงาน...,4,Architecture_and_Engineering,home-inspection,2,72,0,0,0.0,0,2500
4,ตรวจรับบ้านและคอนโด ตรวจสอบขั้นตอนการก่อสร้างข...,5,Architecture_and_Engineering,home-inspection,7,75,0,0,0.0,0,3500

In [97]:
output_file = "aboutTitle.xlsx"
aboutTitle.to_excel(output_file, index=False, engine='openpyxl')
print(f"Merged data has been saved to {output_file}")

Merged data has been saved to aboutTitle.xlsx